// Generated by scripts/build-content.js. Do not edit directly.
(() => {
"use strict";

// ---- lib/dlh-tree.js ----
/** DLH interactive tree — enhanced element detection (v2). */

const REF_ATTR = "data-dlh-ref";
const GEN_KEY = "dlh-ref-generation";

const MAX_NODES = 500;
const MAX_DEPTH = 18;

const TAG_SCORE = {
  button: 90,
  a: 75,
  input: 85,
  textarea: 85,
  select: 80,
  summary: 70,
  label: 55
};

const INTERACTIVE_ROLES = new Set([
  "button",
  "link",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "tab",
  "checkbox",
  "radio",
  "switch",
  "combobox",
  "textbox",
  "searchbox",
  "slider",
  "spinbutton",
  "option",
  "treeitem",
  "gridcell"
]);

function implicitRole(el) {
  const explicit = el.getAttribute?.("role");
  if (explicit) return explicit.toLowerCase();
  const tag = el.tagName?.toLowerCase();
  if (tag === "button") return "button";
  if (tag === "a" && el.getAttribute("href")) return "link";
  if (tag === "input") return el.type || "textbox";
  if (tag === "textarea") return "textbox";
  if (tag === "select") return "combobox";
  if (tag === "summary") return "button";
  if (el.isContentEditable) return "textbox";
  return tag || "generic";
}

function labelOfElement(el, doc = document) {
  const pieces = [
    el.getAttribute("aria-label"),
    labelFromAriaLabelledBy(el, doc),
    el.getAttribute("title"),
    el.getAttribute("placeholder"),
    el.getAttribute("alt"),
    el.getAttribute("name"),
    el.getAttribute("value") && el.tagName === "INPUT" ? el.getAttribute("value") : null,
    labelFromForAttribute(el, doc),
    el.labels?.[0]?.innerText,
    el.innerText
  ];
  for (const piece of pieces) {
    const text = String(piece || "").replace(/\s+/g, " ").trim();
    if (text) return text.slice(0, 140);
  }
  return "";
}

function labelFromAriaLabelledBy(el, doc) {
  const ids = (el.getAttribute("aria-labelledby") || "").split(/\s+/).filter(Boolean);
  if (!ids.length) return "";
  return ids
    .map((id) => doc.getElementById(id)?.innerText || "")
    .join(" ")
    .trim();
}

function labelFromForAttribute(el, doc) {
  if (el.tagName?.toLowerCase() !== "label") return "";
  const id = el.getAttribute("for");
  if (!id) return "";
  const control = doc.getElementById(id);
  if (!control) return "";
  return control.getAttribute("aria-label") || control.getAttribute("placeholder") || control.getAttribute("name") || "";
}

function scoreElement(el, labelText = "") {
  const tag = el.tagName?.toLowerCase();
  const role = implicitRole(el);
  let score = TAG_SCORE[tag] || 0;

  if (INTERACTIVE_ROLES.has(role)) score += 55;
  if (el.getAttribute("role")) score += 25;
  if (el.tabIndex >= 0) score += 25;
  if (el.disabled || el.getAttribute("aria-disabled") === "true") score -= 40;
  if (el.getAttribute("href")) score += 15;
  if (labelText) score += 20;
  if (/^h[1-6]$/i.test(tag) && labelText) score += 35;
  if (el.isContentEditable) score += 70;
  if (el.getAttribute("onclick") || el.onclick) score += 35;
  try {
    if (el.style?.cursor === "pointer") score += 20;
  } catch {
    // ignore
  }
  if (tag === "input" && ["button", "submit", "reset", "checkbox", "radio"].includes(el.type)) score += 30;
  if (tag === "label" && el.getAttribute("for")) score += 25;

  return score;
}

function isVisible(el, getComputedStyleFn = getComputedStyle) {
  if (!el?.getBoundingClientRect) return false;
  const style = getComputedStyleFn(el);
  if (style.display === "none" || style.visibility === "hidden" || Number(style.opacity) === 0) {
    return false;
  }
  if (style.pointerEvents === "none") return false;
  const rect = el.getBoundingClientRect();
  return rect.width > 1 && rect.height > 1;
}

function isAriaHidden(el) {
  if (el.getAttribute("aria-hidden") === "true") return true;
  let parent = el.parentElement;
  let depth = 0;
  while (parent && depth < 6) {
    if (parent.getAttribute("aria-hidden") === "true") return true;
    parent = parent.parentElement;
    depth += 1;
  }
  return false;
}

function isInert(el) {
  if (el.inert || el.getAttribute("inert") !== null) return true;
  let parent = el.parentElement;
  let depth = 0;
  while (parent && depth < 8) {
    if (parent.inert || parent.getAttribute("inert") !== null) return true;
    parent = parent.parentElement;
    depth += 1;
  }
  return false;
}

/** Element center is not fully covered by an unrelated ancestor. */
function isReachableAtCenter(el, doc = document) {
  const rect = el.getBoundingClientRect();
  if (rect.width < 2 || rect.height < 2) return false;
  const x = clamp(rect.left + rect.width / 2, rect.left + 1, rect.right - 1);
  const y = clamp(rect.top + rect.height / 2, rect.top + 1, rect.bottom - 1);
  const hit = doc.elementFromPoint(x, y);
  if (!hit) return false;
  return hit === el || el.contains(hit) || hit.contains(el);
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function openShadowRoot(el) {
  if (el.shadowRoot) return el.shadowRoot;
  try {
    return chrome?.dom?.openOrClosedShadowRoot?.(el) || null;
  } catch {
    return null;
  }
}

function nextRefGeneration(storage) {
  const current = Number(storage.getItem(GEN_KEY) || 0);
  const next = current + 1;
  storage.setItem(GEN_KEY, String(next));
  return next;
}

function assertRefGeneration(expected, storage) {
  if (expected === undefined || expected === null) return;
  const live = Number(storage.getItem(GEN_KEY) || 0);
  if (Number(expected) !== live) {
    throw new Error(
      `Stale snapshot (expected refGeneration ${expected}, current ${live}). Call dlh_browser_snapshot again.`
    );
  }
}

function inputMeta(el) {
  const tag = el.tagName?.toLowerCase();
  if (tag !== "input") return "";
  const parts = [el.type || "text"];
  if (el.required) parts.push("required");
  if (el.readOnly) parts.push("readonly");
  return ` <input ${parts.join(" ")}>`;
}

function stateOf(el, doc) {
  const parts = [];
  if (el.disabled || el.getAttribute("aria-disabled") === "true") parts.push("disabled");
  if (el.checked) parts.push("checked");
  if (el === doc.activeElement) parts.push("focused");
  const expanded = el.getAttribute("aria-expanded");
  if (expanded === "true") parts.push("expanded");
  if (expanded === "false") parts.push("collapsed");
  if (el.getAttribute("aria-pressed") === "true") parts.push("pressed");
  if (!isReachableAtCenter(el, doc)) parts.push("obscured");
  return parts.length ? ` {${parts.join(", ")}}` : "";
}

function shortPath(el) {
  const bits = [];
  let node = el;
  while (node && node.nodeType === 1 && bits.length < 5) {
    const tag = node.tagName?.toLowerCase() || "node";
    const id = node.id ? `#${node.id}` : "";
    const testId = node.getAttribute?.("data-testid");
    const testBit = testId ? `[data-testid=${testId}]` : "";
    bits.unshift(`${tag}${id}${testBit}`);
    node = node.parentElement || node.getRootNode()?.host || null;
  }
  return bits.join(" > ");
}

function buildInteractiveTree(root, { doc = document, getComputedStyleFn = getComputedStyle, storage = sessionStorage } = {}) {
  root.querySelectorAll(`[${REF_ATTR}]`).forEach((el) => el.removeAttribute(REF_ATTR));

  const refGeneration = nextRefGeneration(storage);
  const ELEMENT_NODE = doc.defaultView?.Node?.ELEMENT_NODE ?? 1;
  const lines = [];
  const index = [];
  let assigned = 0;
  const stack = [{ el: root.documentElement || root, depth: 0 }];

  function pushChildren(el, depth) {
    const kids = el.children ? Array.from(el.children) : [];
    for (let i = kids.length - 1; i >= 0; i -= 1) stack.push({ el: kids[i], depth: depth + 1 });
    const shadow = openShadowRoot(el);
    if (shadow) {
      const shadowKids = Array.from(shadow.children);
      for (let i = shadowKids.length - 1; i >= 0; i -= 1) stack.push({ el: shadowKids[i], depth: depth + 1 });
    }
  }

  while (stack.length && assigned < MAX_NODES) {
    const { el, depth } = stack.pop();
    if (!el || depth > MAX_DEPTH) continue;

    if (el.nodeType !== ELEMENT_NODE || isAriaHidden(el) || isInert(el)) {
      pushChildren(el, depth);
      continue;
    }

    if (!isVisible(el, getComputedStyleFn)) {
      pushChildren(el, depth);
      continue;
    }

    const name = labelOfElement(el, doc);
    const score = scoreElement(el, name);
    const tag = el.tagName?.toLowerCase();
    const role = implicitRole(el);
    const interesting = score >= 48 || (name && /^h[1-6]$/i.test(tag));

    if (interesting) {
      assigned += 1;
      const ref = `@${assigned}`;
      el.setAttribute(REF_ATTR, ref);
      const indent = "  ".repeat(Math.min(depth, 8));
      const meta = inputMeta(el);
      lines.push(`${indent}${ref} [${role}] ${name || "(no label)"}${stateOf(el, doc)}${meta}  <${shortPath(el)}>`);
      index.push({ ref, role, name: name || "", score, obscured: !isReachableAtCenter(el, doc) });

      if (tag === "select") {
        const opts = Array.from(el.options || [])
          .slice(0, 16)
          .map((o) => `${o.value}=${o.label || o.text}`)
          .join(", ");
        if (opts) lines.push(`${indent}  options: ${opts}`);
      }
    }

    pushChildren(el, depth);
  }

  return {
    format: "dlh-tree-v2",
    refPrefix: "@",
    refGeneration,
    refCount: assigned,
    snapshot: lines.join("\n"),
    index
  };
}

/** Search the indexed snapshot entries (case-insensitive substring). */
function findInIndex(index, query, { limit = 12 } = {}) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return [];
  return index
    .filter((entry) => entry.name.toLowerCase().includes(q) || entry.role.includes(q) || entry.ref.includes(q))
    .sort((a, b) => b.score - a.score)
    .slice(0, limit);
}

// ---- page/context.js ----
/** DLH page context — structured extraction for Cursor prompts (DLH-native, not markdown-clone). */

const EXCERPT_LIMIT = 24_000;
const SELECTION_LIMIT = 12_000;

function cleanText(value, limit) {
  return String(value || "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, limit);
}

function articleRoot() {
  return (
    document.querySelector("article") ||
    document.querySelector("[role='main']") ||
    document.querySelector("main") ||
    document.body
  );
}

function headingOutline(root) {
  const headings = root.querySelectorAll("h1, h2, h3, h4, h5, h6");
  const outline = [];
  for (const el of headings) {
    if (outline.length >= 12) break;
    const text = cleanText(el.innerText, 160);
    if (!text) continue;
    outline.push({ level: el.tagName.toLowerCase(), text });
  }
  return outline;
}

function paragraphSample(root) {
  const blocks = [];
  for (const el of root.querySelectorAll("p, li, pre, blockquote")) {
    if (blocks.length >= 8) break;
    const text = cleanText(el.innerText, 320);
    if (text.length < 40) continue;
    blocks.push(text);
  }
  return blocks;
}

function getPageContext(workspaceId = null) {
  const root = articleRoot();
  const excerptSource = cleanText(root?.innerText || "", EXCERPT_LIMIT);
  return {
    url: location.href,
    title: document.title,
    selection: cleanText(getSelection?.() || "", SELECTION_LIMIT),
    excerpt: excerptSource,
    outline: headingOutline(root),
    blocks: paragraphSample(root),
    workspaceId: workspaceId ?? null,
    capturedAt: new Date().toISOString()
  };
}

// ---- page/snapshot.js ----
/** DLH snapshot in a single frame. */

function buildSnapshot() {
  const tree = buildInteractiveTree(document, { doc: document, storage: sessionStorage });
  return {
    url: location.href,
    title: document.title,
    frameId: window === window.top ? 0 : null,
    ...tree
  };
}

function findElements(query, limit = 12) {
  const tree = buildSnapshot();
  return {
    refGeneration: tree.refGeneration,
    matches: findInIndex(tree.index, query, { limit })
  };
}

function elementForRef(ref, refGeneration) {
  assertRefGeneration(refGeneration, sessionStorage);
  if (!ref || !String(ref).startsWith("@")) {
    throw new Error(`Invalid DLH ref "${ref}". Use refs from dlh_browser_snapshot (e.g. @12).`);
  }
  const el = document.querySelector(`[${REF_ATTR}="${CSS.escape(ref)}"]`);
  if (!el) {
    throw new Error(`Ref ${ref} not found. Call dlh_browser_snapshot again after navigation or DOM changes.`);
  }
  return el;
}

// ---- page/actions.js ----
function centerOf(el) {
  const rect = el.getBoundingClientRect();
  return {
    x: rect.left + rect.width / 2,
    y: rect.top + rect.height / 2
  };
}

function dispatchPointer(el, type, init) {
  el.dispatchEvent(new PointerEvent(type, { bubbles: true, cancelable: true, composed: true, ...init }));
}

/** Prefer real control for labels; climb to nearest explicit interactive ancestor. */
function resolveActionTarget(el) {
  const tag = el.tagName?.toLowerCase();
  if (tag === "label") {
    const id = el.getAttribute("for");
    if (id) {
      const control = document.getElementById(id);
      if (control) return control;
    }
  }

  return (
    el.closest(
      "button, a[href], input, select, textarea, summary, [role='button'], [role='link'], [role='menuitem'], [contenteditable='true']"
    ) || el
  );
}

function measureRef(ref, refGeneration) {
  let el = elementForRef(ref, refGeneration);
  el = resolveActionTarget(el);
  el.scrollIntoView({ block: "center", inline: "nearest" });
  const rect = el.getBoundingClientRect();
  return {
    x: Math.round(rect.left + rect.width / 2),
    y: Math.round(rect.top + rect.height / 2)
  };
}

function clickRef(ref, refGeneration, button = "left", clickCount = 1) {
  let el = elementForRef(ref, refGeneration);
  el = resolveActionTarget(el);

  if (el.disabled || el.getAttribute("aria-disabled") === "true") {
    throw new Error(`Ref ${ref} is disabled.`);
  }

  el.scrollIntoView({ block: "center", inline: "nearest" });
  const { x, y } = centerOf(el);
  const pointerInit = {
    pointerId: 1,
    pointerType: "mouse",
    isPrimary: true,
    clientX: x,
    clientY: y,
    button: button === "right" ? 2 : 0,
    buttons: button === "right" ? 2 : 1
  };

  for (let i = 0; i < clickCount; i += 1) {
    dispatchPointer(el, "pointerover", pointerInit);
    dispatchPointer(el, "pointerenter", pointerInit);
    dispatchPointer(el, "pointerdown", pointerInit);
    dispatchPointer(el, "pointerup", pointerInit);
    el.dispatchEvent(
      new MouseEvent("click", {
        bubbles: true,
        cancelable: true,
        composed: true,
        clientX: x,
        clientY: y,
        button: pointerInit.button,
        detail: i + 1
      })
    );
    if (typeof el.click === "function") el.click();
  }

  const hit = document.elementFromPoint(x, y);
  const hitRef = hit?.closest?.(`[data-dlh-ref]`)?.getAttribute("data-dlh-ref") || null;

  return {
    ok: true,
    ref,
    tag: el.tagName,
    actionTarget: el.tagName,
    hitRef: hitRef !== ref ? hitRef : null
  };
}

function typeRef(ref, refGeneration, text, submit = false) {
  const el = resolveActionTarget(elementForRef(ref, refGeneration));
  el.focus({ preventScroll: false });

  if ("value" in el) {
    el.value = text;
    el.dispatchEvent(new InputEvent("input", { bubbles: true, data: text, inputType: "insertText" }));
    el.dispatchEvent(new Event("change", { bubbles: true }));
  } else if (el.isContentEditable) {
    el.textContent = text;
    el.dispatchEvent(new InputEvent("input", { bubbles: true, data: text, inputType: "insertText" }));
  } else {
    throw new Error(`Ref ${ref} is not a text input.`);
  }

  if (submit) {
    el.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", code: "Enter", bubbles: true }));
    el.form?.requestSubmit?.();
  }

  return { ok: true, ref, length: text.length };
}

function fillRef(ref, refGeneration, text) {
  return typeRef(ref, refGeneration, text, false);
}

function selectRef(ref, refGeneration, value) {
  const el = elementForRef(ref, refGeneration);
  if (el.tagName?.toLowerCase() !== "select") {
    throw new Error(`Ref ${ref} is not a <select> element.`);
  }
  const options = Array.from(el.options || []);
  const match =
    options.find((o) => o.value === value) ||
    options.find((o) => (o.label || o.text).trim() === value) ||
    options.find((o) => (o.label || o.text).toLowerCase().includes(String(value).toLowerCase()));
  if (!match) throw new Error(`Option "${value}" not found on select ${ref}.`);
  el.value = match.value;
  el.dispatchEvent(new Event("input", { bubbles: true }));
  el.dispatchEvent(new Event("change", { bubbles: true }));
  return { ok: true, ref, value: match.value, label: match.label || match.text };
}

function scrollPage(direction = "down", amount = 900) {
  const target = document.scrollingElement || document.documentElement;
  const delta = direction === "up" ? -Math.abs(amount) : Math.abs(amount);
  target.scrollBy({ top: delta, behavior: "smooth" });
  return {
    ok: true,
    direction,
    scrollTop: target.scrollTop,
    scrollHeight: target.scrollHeight
  };
}

function waitMs(ms) {
  return new Promise((resolve) => {
    setTimeout(() => resolve({ ok: true, waitedMs: ms }), ms);
  });
}

// ---- content.entry.js ----
let cachedWorkspaceId = null;

async function resolveWorkspaceId() {
  if (cachedWorkspaceId !== null) return cachedWorkspaceId;
  try {
    const response = await chrome.runtime.sendMessage({ type: "DLH_GET_WORKSPACE" });
    cachedWorkspaceId = response?.workspaceId ?? null;
  } catch {
    cachedWorkspaceId = null;
  }
  return cachedWorkspaceId;
}

async function runPageCommand(command, params = {}) {
  const refGeneration = params.refGeneration;
  switch (command) {
    case "snapshot":
      return buildSnapshot();
    case "find":
      return findElements(params.query, params.limit);
    case "measureRef":
      return measureRef(params.ref, refGeneration);
    case "click":
      return clickRef(params.ref, refGeneration, params.button, params.clickCount);
    case "type":
      return typeRef(params.ref, refGeneration, params.text || "", Boolean(params.submit));
    case "fill":
      return fillRef(params.ref, refGeneration, params.text || "");
    case "select":
      return selectRef(params.ref, refGeneration, params.value);
    case "scroll":
      return scrollPage(params.direction, Number(params.amount || 900));
    case "wait":
      return waitMs(Number(params.ms || 1000));
    default:
      throw new Error(`Unknown page command: ${command}`);
  }
}

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message.type === "DLH_VIVALDI_WORKSPACE") {
    cachedWorkspaceId = message.workspaceId ?? null;
    sendResponse?.({ ok: true });
    return false;
  }

  if (message.type === "DLH_GET_PAGE_CONTEXT") {
    (async () => {
      const workspaceId = await resolveWorkspaceId();
      sendResponse(getPageContext(workspaceId));
    })();
    return true;
  }

  if (message.type === "DLH_PAGE_COMMAND") {
    (async () => {
      try {
        sendResponse({ ok: true, result: await runPageCommand(message.command, message.params || {}) });
      } catch (error) {
        sendResponse({ ok: false, error: error?.message || String(error) });
      }
    })();
    return true;
  }

  return false;
});

})();
