import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const extensionRoot = join(projectRoot, "extension");

const sources = [
  "lib/dlh-tree.js",
  "page/context.js",
  "page/snapshot.js",
  "page/actions.js",
  "content.entry.js"
];

function toClassicScript(source) {
  return source
    .replace(/^import\s+[^;]+;\s*$/gm, "")
    .replace(/^export\s+(const|let|var|function|class)\s+/gm, "$1 ")
    .replace(/^export\s*\{[^}]+\};?\s*$/gm, "");
}

const parts = [];
for (const file of sources) {
  const source = await readFile(join(extensionRoot, file), "utf8");
  parts.push(`// ---- ${file} ----\n${toClassicScript(source).trim()}\n`);
}

const bundle = `// Generated by scripts/build-content.js. Do not edit directly.\n(() => {\n\"use strict\";\n\n${parts.join("\n")}\n})();\n`;

await writeFile(join(extensionRoot, "content.js"), bundle, "utf8");
console.log("Built extension/content.js classic content script bundle.");
